# Generated by Django 3.0.4 on 2020-05-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adtool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='identification_key',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
