# Generated by Django 3.0.4 on 2020-05-19 04:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adtool', '0002_advertisement_identification_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementlog',
            name='is_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisementlog',
            name='unique_key',
            field=models.CharField(default='0', max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='advertisementlog',
            name='view_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date viewed'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.IntegerField(choices=[(0, 'science'), (1, 'math'), (2, 'anime'), (3, 'computers'), (4, 'nature'), (5, 'news'), (6, 'music'), (7, 'politics'), (8, 'anthology'), (9, 'medical'), (10, 'sports'), (11, 'fashion'), (12, 'others')], default='others'),
        ),
        migrations.AlterField(
            model_name='advertisementlog',
            name='click_date',
            field=models.DateTimeField(default=None, verbose_name='date clicked'),
        ),
    ]
