# Generated by Django 3.0.4 on 2020-05-19 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adtool', '0004_auto_20200519_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementlog',
            name='click_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date clicked'),
        ),
    ]
